club/urls.py
from django.urls import path

from . import views

app_name = 'club'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:club_id>/', views.detail, name='detail'),
    path('update/<int:club_id>/', views.update, name='update'),
    path('appli/<int:club_id>', views.appli, name='appli'),
    path('accept', views.accept, name='accept')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('club/', include('club.urls'), name='club'),
    path('event/', include('event.urls'), name='event'),
    path('post/', include('post.urls'), name='post'),
]

event/urls.py
from django.urls import path

from . import views

app_name = 'event'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:event_month>/', views.index, name='index'),
    path('detail/<int:event_id>/', views.detail, name='detail'),
    path('registration/', views.registration, name='registration'),
]

home/urls.py
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    #path('register/', views.register, name='register'),
    path('checkid/', views.checkmail, name='checkmail'),
    path('login/', auth_views.LoginView.as_view(template_name='home/home_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user/', views.user, name='user'),
    path('user/<int:userid>', views.user, name='user'),
    path('edit/', views.edit, name='edit'),
    path('manage/', views.manage, name='manage'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),
    #path('usercreate/', views.accountcreate, name='usercreate'),
]

post/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.postdetail, name='postdetail'),
    path('notice/<int:notice_id>/', views.noticedetail, name='noticedetail'),
    path('write', views.write, name='write'),
    path('like', views.like, name='like'),
    path('comment/write/<int:post_id>', views.commentwrite, name='commentwrite'),
    #path('testcase/', views.testcase, name='testcase')
]

home/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User as djangoUser
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

class User(models.Model):
    name = models.CharField(max_length=20)
    type = models.CharField(max_length=20)
    year = models.IntegerField(default=2021)
    number = models.IntegerField()
    regi_date = models.DateField(auto_created=True)
    django_user = models.ForeignKey(djangoUser, on_delete=CASCADE)
    email = models.EmailField()
    profile_message = models.CharField(max_length=200, default=' ')
    interested_in = models.CharField(max_length=20, default=' ')
    description = models.TextField(default='', blank=True)
    lastedit = models.DateField(auto_now=True, auto_now_add=False)
    like = models.TextField(default='/', blank=True)
    noticelike = models.TextField(default='/', blank=True)

    def __str__(self):
        if self.type == 'Student':
            return str(self.number) + " " + self.name
        else:
            return self.name

class UserLoginLog(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=CASCADE, )
    ip_address = models.GenericIPAddressField(verbose_name=_('IP Address'))
    logged = models.DateTimeField(auto_created=True)
    
    def __str__(self):
        return '%s %s' % (self.user, self.ip_address)

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User as djangoUser

class UserForm(forms.Form):
    email = forms.EmailField(label='이메일')
    username = forms.CharField(max_length=32, label='아이디')
    name = forms.CharField(max_length=20, label='이름')
    number = forms.IntegerField(label='학번')
    password1 = forms.CharField(widget=forms.PasswordInput, label='비밀번호')
    password2 = forms.CharField(widget=forms.PasswordInput, label='비밀번호 확인')
    
    fields = ('email', 'username', 'name', 'number', 'password1', 'password2')
    
    def clean(self):
        cleaned_data = super().clean()
        
class djangoUserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    
    class Meta:
        model = djangoUser
        fields = ("username", "password1", "password2", "email")
        
class profileForm(forms.Form):
    profile_message = forms.CharField(max_length=200)
    interested_in = forms.CharField(max_length=20)
    description = forms.CharField()
    
    fields = ('profile_message', 'interested_in', 'description')
    
    def clean(self):
        cleaned_data = super().clean()

home/views.py
import requests
from bs4 import BeautifulSoup
from datetime import datetime
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text

from config.pd_setting import CURRENT_YEAR
from .tokens import account_activation_token
from .forms import UserForm, djangoUserForm, profileForm
from .models import User, UserLoginLog
from django.utils import timezone
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User as djangoUser
from django.contrib.auth.forms import UserCreationForm
from club.models import Club
from ipware.ip import get_client_ip
from post.models import Notice, Post
from django.db.models import Q
import numpy as np
from event.models import Event
from datetime import timedelta, date, time, timezone as tz

def findclub(user):
    clubs = []
    for club in Club.objects.filter(year=CURRENT_YEAR):
        if user.id in map(int, club.member_detail.split(',')):
            clubs.append(club)
    return clubs

def index(request):
    class day():
        
        def __init__(self, date):
            self.date = date
            self.event = False
            self.today = False
        
        def __str__(self):
            return self.event
        
        def __repr__(self):
            return str(self.event)
        
    if request.user.is_authenticated:
        log = UserLoginLog(
            user = User.objects.get(django_user=request.user),
            ip_address = get_client_ip(request),
            logged = timezone.now()
        )
        log.save()
    q = Q()
    q.add(Q(hotDate__gte=timezone.localtime()), q.AND)
    q.add(Q(publicDate__lte=timezone.localtime()), q.AND)
    notice_list = Notice.objects.order_by('-create_date').filter(q)[:3]
    hot_list = Post.objects.order_by('-create_date').filter(isprivate=False, like__gte=5)[:3]
    
    #행사 목록 불러오는 코드
    today = timezone.localtime()
    startdate = date(year = today.year, month = today.month, day=1)
    
    mt = (startdate.weekday()+1)%7 # 월요일==0+1 .... 일요일==6+1
    startdate = startdate - timedelta(days = mt)  #달력의 공칸 만큼 시작일 연기()
    
    sd = datetime.combine(startdate, time(), tz(timedelta(hours=9)))
    events = Event.objects.filter(start_date__gte=sd).filter(end_date__lte=sd+timedelta(days=35)).order_by('start_date')
    
    month = []
    for i in range(35):
        month.append(day(startdate + timedelta(days = i)))
    for event in events:
        for d in month:
            if event.start_date <= d.date <= event.end_date:
                d.event = True
            if d.date == event.end_date:
                break
    for d in month:
        if today.date() == d.date:
            d.today = True
    month = np.reshape(month, (5,7))
    
    webpage = requests.get("https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%ED%99%94%EB%AA%85%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90&oquery=%ED%99%94%EB%AA%85%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90+%EA%B8%89%EC%8B%9D%EC%8B%9D%EB%8B%A8&tqi=hkVTosp0YihssZiaVCdssssstGC-306582")
    soup = BeautifulSoup(webpage.content, "html.parser")
    #title = soup.select_one("#main_pack > div.sc_new.cs_common_module.case_normal.color_23._school.cs_kindergarten._edu_list > div.cm_content_wrap > div:nth-child(3) > div > div.scroll_box._button_scroller > div > div > ul > li:nth-child(1) > div > div > ul")
    today_menus = soup.select_one("div.time_normal_list")
    menu = today_menus = today_menus.select("ul > li")
    sendmenu = []

    for m in menu:
        sendmenu.append(m.text)

    print(sendmenu)
    
    #html로 보낼 거
    context = {
        'notice_list': notice_list,
        'hot_list': hot_list,
        'month': month,
        'menu': sendmenu,
    }
    return render(request, 'home/home_main.html', context)

def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.clean()
            try:
                djangoUser.objects.get(username=form.cleaned_data.get('username'))
            except:
                userForm = djangoUserForm(request.POST
#                   username = request.POST.get('username'),
#                   password1 = request.POST.get('password1'),
#                   password2 = request.POST.get('password2'),
#                   email = request.POST.get('email')
                )
                if userForm.is_valid():
                    nowuser = userForm.save()
                    nowuser.save()
                    nowuser.is_active = False
                    nowuser.save()
                    #nowuser = djangoUser.objects.order_by('id')
                    user = User(name=form.cleaned_data.get('name'), 
                                number=form.cleaned_data.get('number'),
                                regi_date = timezone.now(),
                                type = 'Student',
                                email = form.cleaned_data.get('email'),
                                django_user = nowuser,
                                profile_message = '',
                                interested_in = '',
                                description = '')
                    user.save()
                    log = UserLoginLog(
                        user = user,
                        ip_address = get_client_ip(request),
                        logged = timezone.now()
                    )
                    log.save()
                    message = render_to_string('home/activation_email.html',
                        {
                            'user': nowuser,
                            'domain': request.get_host(),
                            'uid': urlsafe_base64_encode(force_bytes(nowuser.pk)),
                            'token': account_activation_token.make_token(nowuser),
                        })
                    mail_title = "계정 활성화 확인 이메일"
                    email = EmailMessage(mail_title, message, to=[nowuser.email])
                    email.send()
                    
                    #userForm.username = form.username
                    #userForm.password1 = form.password1
                    #userForm.password2 = form.password2
                    #loginuser = authenticate(username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password'))
                    #login(loginuser)
                    return redirect('home:login')
                    """
                    djangouser = djangoUser(username = form.cleaned_data.get('id'),
                                            password = form.password1,
                                            email = form.cleaned_data.get('email'))
                    djangouser.save()
                    """
                else:
                    return render(request, 'error.html', {'text': 
["유효하지 않은 값입니다.",
"1. 비밀번호 확인을 잘못 입력한 경우",
"2. 비밀번호가 너무 짧은 경우",
"3. 이메일이 이미 사용된 경우",
]})
            else:
                return render(request, 'error.html', {'text': ["중복된 아이디입니다."]})
        else:
            return render(request, 'error.html', {'text': ["유효하지 않은 값입니다."]})
    else:
        form = UserForm()
        return render(request, 'home/home_register.html', {'form':form})

def login(request):
    return render(request, 'home/home_login.html')

def user(request, userid = None):
    if userid:
        try:
            du = djangoUser.objects.get(id=userid)
            user = User.objects.get(django_user = du)
            clubs = findclub(du)
        except:
            return render(request, 'error.html', {'text': ["존재하지 않는 유저입니다."]})
        else:
            context = {
                'myuser': user,
                'clubs': clubs
            }
            return render(request, 'home/home_user.html', context)
    else:
        if request.user.is_authenticated:
            user = User.objects.get(django_user = request.user)
            clubs = findclub(request.user)
            context = {
                'myuser': user,
                'clubs': clubs
            }
            return render(request, 'home/home_user.html', context)
        else:
            return render(request, 'error.html', {'text':[ "로그인 되어 있지 않습니다."]})

def checkmail(request):
    try:
        user = djangoUser.objects.get(username=request.GET['username'])
    except Exception as e:
        user = None
    result = {
        'result':'success',
        'data':'not exist' if user is None and len(request.GET['username']) >= 5 else 'exist'
    }
    return JsonResponse(result)

def edit(request):
    if request.user.is_authenticated:
        user = User.objects.get(django_user = request.user)
        if request.method == 'POST':
            user.profile_message = str(request.POST.get('profilemessage'))
            user.interested_in = str(request.POST.get('interestedin'))
            user.description = request.POST.get('description')
            user.last_edit = datetime.now
            user.save()
            return redirect('home:index')
        else:
            context = {
                'myuser': user
            }
            return render(request, 'home/home_edit.html', context)
    else:
        return render(request, 'error.html', {'text': ["로그인 되어 있지 않습니다."]})

def manage(request):
    if request.user.is_authenticated:
        user = User.objects.get(django_user = request.user)
        club_list = Club.objects.filter(club_master=user)
        context = {
            'club_list': club_list
        }
        return render(request, 'home/home_manage.html', context)
    else:
        return render(request, 'error.html', {'text':['로그인 되어 있지 않습니다.']})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))

templates/home/activation_email.html
{{user.username}}님 안녕하세요,
아래 링크를 클릭하여 계정을 활성화시킨 이후 로그인해주시길 바랍니다.
http://{{domain}}{% url 'home:activate' uid token %}

templates/home/home_edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}마이페이지 수정{% endblock title %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/home_edit.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
{% endblock style %}
{% block content %}
    <div class="d-flex flex-column">
        <div class="d-flex title justify-content-center">
            <h1>마이페이지 수정</h1>
        </div>
        <div class="d-flex justify-content-center">
            <div class="max">
                <form method="post" class="post-form my-3" action="{% url 'home:edit' %}">
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                        {% for field in form %}
                            {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                            {% endif %}
                        {% endfor %}
                        </div>
                    {% endif %}
                    <div class="form-group col">
                        <label for="profileMessage">상태메시지(아래 글의 제목)</label>
                        <input name="profilemessage" type="text" class="form-control" maxlength="200"
                        value="{{myuser.profile_message}}" id="profileMessage" placeholder="자신을 소개하는 문구, 아래 글의 제목">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="interestedIn">관심사</label>
                        <input name="interestedin" type="text" class="form-control" id="interestedIn" placeholder="관심사"
                        value="{{myuser.interested_in}}" maxlength="20">
                    </div>
                    <div class="form-group col">
                        <label for="interestedIn">자신을 소개하는 글</label>
                        <textarea name="description" type="description" id="Description">{{myuser.description}}</textarea>
                        <script>
                            var simplemde = new SimpleMDE({ 
                                element: $("#Description")[0],
                                spellChecker: false
                                });
                        </script>
                    </div>
                    <button type="submit" class="btn btn-primary">저장하기</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/home/home_login.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/home_login.css' %}">
{% endblock style %}
{% block title %}로그인{% endblock title %}
{% block content %}
<div class="container my-3">
    <form method="post", class="post-form", action="{% url 'home:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                    value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호 <a style="font-size:.75em;"href="{% url 'home:password_reset' %}">(비밀번호를 잊으셨나요?)</a></label>
            <input type="password" class="form-control" name="password" id="password"
                    value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="d-flex">
            <button type="submit" class="btn btn-primary">로그인</button>
            {% comment %} <a href="{% url 'home:register' %}" class="button btn btn-primary sign-btn">회원가입</a> {% endcomment %}
        </div>
    </form>
</div>
{% endblock content %}

templates/home/home_main.html
{% extends 'base.html' %}
{% load static %}
{% load home_filter %}
{% load compress %}
{% compress css %}
{% comment %} <link rel="stylesheet" type="text/x-scss" href="{% static 'css/home_main.scss' %}"> {% endcomment %}
{% endcompress %}
{% block style %}{{ block.super }}
<link rel="stylesheet" href="{% static 'css/home_main.css' %}">
<script src={% static 'js/home_main.js' %}></script>
{% comment %} <link rel="stylesheet" href="{% static 'css/home_main_sub.css' %}"> {% endcomment %}
{% comment %} <style type="text/css">
	body {
		background-color: #F3FFFF;
	}
</style> {% endcomment %}
{% comment %} <script src={% static 'js/vue.js' %}></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script> {% endcomment %}
<script>
	{% comment %} var jsonpath = "{% static 'json/home_pic.json' %}"; {% endcomment %}
</script>
<!--해드부분 -->
{% endblock style %}
{% block title %}화명고 동아리 행사{% endblock title %}
{% block content %}
 <!-- 바디부분 -->
<div class="menu-btn">
    <i class="fas fa-bars fa-2x"></i>
  </div>

  <div class="container">
    </nav>
    <!-- Showcase -->
    <header class="showcase">
    </header>

    <section class="fulldiv">
      <div class="d-flex boxboxbox"style="background-color:#CCCCCC; padding:20px;">
        <div class="postbox flex-column">
          <div class="noticebox boxbox">
            <h3>공지사항</h3>
            <ul>
            {% for notice in notice_list %}
              <li><a class="link_a" href="{% url 'post:noticedetail' notice.id %}">{{notice.title}}</a></li>
            {% endfor %}
            </ul>
          </div>
          <div class="hotbox boxbox">
            <h3>인기글</h3>
            <ul>
            {% for hot in hot_list %}
              <li><a class="link_a" href="{% url 'post:postdetail' hot.id %}">{{hot.title}}</a></li>
            {% endfor %}
            </ul>
          </div>
        </div>
        <div class="eventbox boxbox">
          <a class="link_a" href="{% url 'event:index' %}">
          <h3 class="d-flex">행사 달력<h3>
          <table class="calendar">
            <thead>
              <tr class="calendarhead">
                <th>S</th><th>M</th><th>T</th><th>W</th><th>T</th><th>F</th><th>S</th>
              </tr>
            </thead>
            <tbody>
              {% for week in month %}
              <tr class="calendarhead calendarbody">
                {% for day in week %}
                  <td>
                    {% if day.today %}
                    <p class="datetext today">{{day.date | strf}}</p>
                    {% elif day.event %}
                    <p class="datetext eventday">{{day.date | strf}}</p>
                    {% else %}
                    <p class="datetext">{{day.date | strf}}</p>
                    {% endif %}
                  </td>
                {% endfor %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
          </a>
        </div>
      </div>
    </section>

    <!-- Home cards 1 -->
    <section class="home-cards">
      <div>
        <a href="{% url 'club:index' %}">
        <img src="https://ifh.cc/g/R43QkC.jpg" alt="">
        </a>
        <h3>동아리</h3>
        <p>저희 학교에는 여러 동아리들이 존재합니다. 과학, 생태, 경제, 예술, 기술, 스포츠, 댄스 등 다양한 분야로 학생들의 주도하는 동아리들이 개설되어 있습니다.
        </p>
      </div>
      <div>
        <a href="{% url 'event:index' %}">
        <img src="https://ifh.cc/g/s1uJPf.jpg" alt="" />
        </a>
        <h3>행사</h3>
        <p>화명고등학교의 월별 행사, 학사일정에 대해 소개하는 페이지 입니다.
          
        </p>
      </div>
      <div>
        <a href="{% url 'post:index' %}">
        <img src="https://ifh.cc/g/v8SL1Z.jpg" alt="" />
        </a>
        <h3>게시판</h3>
        <p>자유롭게 이야기를 나눌 수 있는 공간입니다. 가상의 공간에서 자유롭게 대화를 이어나가보세요.
          
        </p>
      </div>
      <div>
        <a href="{% url 'home:user' %}">
        <img src="https://ifh.cc/g/ZmIoxB.jpg" alt="" />
        </a>
        <h3>기타</h3>
        <p>
        기타는 딩기딩
        </p>
      </div>
    </section>

    <!-- Xbox -->
    <section class="xbox">
      <div class="content">
        <h2>화명고등학교</h2>
        <p>화명고등학교에 더 궁금한 부분이 있다면 홈페이지를 직접 방문 해보시길 바랍니다.</p>
          <a href="#" class="btn"onclick="location.href='https://school.busanedu.net/hwamyeong-h/main.do'">
            바로가기 <i class="fas fa-chevron-right"></i>
          </a>
      </div>
    </section>


    <!-- Home cards 2 -->
			<section class="home-cards">
        <div class="food"style="background-color:#CCCCCC; padding:20px;">
        <h2>오늘의 급식</h2>
        <p>
          {% for m in menu %}
          <p2>{{m}},</p2>
          {% endfor %}
        </p>
        </div>
      </section>
{% endblock content %}

templates/home/home_manage.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/home_manage.css' %}">
{% endblock style %}
{% block title %}동아리/행사 관리{% endblock title %}
{% block content %}
<div class="d-flex flex-column">
    <div class="d-flex title justify-content-center">
        <h2 class="titletext">동아리/행사 관리</h2>
    </div>
    <div class="list">
        <h4 class="listindex">동아리 목록</h4>
        <ul>
            {% for club in club_list %}
                <li><a class="clubname" href="{% url 'club:update' club.id %}">{{club.name}}</a></li>
            {% endfor %}
        </ul>
        <h4 class="listindex">행사 목록</h4>
        <ul>
            {% comment %} {% for club in club_list %}
                <li><a class="clubname" href="">{{club.name}}</a></li>
            {% endfor %} {% endcomment %}
        </ul>
    </div>
</div>
{% endblock content %}

templates/home/home_myPage.html
{% extends 'base.html' %}
{% block title %}마이페이지{% endblock title %}
{% block content %}
    <div class="d-flex center flex-column ">
        <div class="title d-flex justify-content-center">
            <h1>마이페이지</h1>
        </div>
        {% if myuser %}
            <div class="name">
                <h2>{{myuser.number}} {{myuser.name}}</h2>
                <h3>이메일</h3>
                <h3>{{myuser.email}}</h3>
            </div>
        {% endif %}
    </div>
{% endblock content %}

templates/home/home_register.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/home_register.css' %}">
<script src="{% static 'js/home_register.js' %}"></script>
{% endblock style %}
{% block content %}
<div class="container">
    <form method="post" class="post-form my-3" action="{% url 'home:register' %}">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="name">이름</label>
            <input type="text" class="form-control" name="name" id="name"
                    value="{{ form.name.value|default_if_none:'' }}" maxlength="20">
        </div>
        <div class="form-group">
            <label for="username">아이디</label>
            <input class="form-control" name="username"
                        id="username" onchange="check()" rows="10">{{ form.username.value|default_if_none:'' }}</input>
            <p id="idcheck">사용할 수 없는 아이디입니다.</p>
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input class="form-control" name="password1", type="password"
                        id="password1" rows="10">{{ form.password1.value|default_if_none:'' }}</input>
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input class="form-control" name="password2", type="password"
                        id="password2" rows="10">{{ form.password2.value|default_if_none:'' }}</input>
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input class="form-control" name="email"
                        id="email" rows="10">{{ form.email.value|default_if_none:'' }}</input>
            <p class="emailverify">회원가입이 정상적으로 이루어지면 인증 이메일이 발송됩니다.</p>
            <p class="emailverify">이메일 인증 이후 로그인이 가능합니다.</p>
            <p class="emailverify">이메일 전송에는 시간이 걸릴 수 있습니다.</p>
        </div>
        <div class="form-group">
            <label for="number">학번</label>
            <input class="form-control" name="number"
                        id="number" rows="10" maxlength="6">{{ form.number.value|default_if_none:'' }}</input>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock content %}

templates/home/home_user.html
{% extends 'base.html' %}
{% load static %}
{% load home_filter %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/home_user.css' %}">
<style>
    .img {
        background-image: url({% static 'img/background.png' %});
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
{% endblock style %}
{% block title %}{{myuser.number}} {{myuser.name}}{% endblock title %}
{% block content %}
<div class="">
    <div class="d-flex center flex-column ">
        {% if myuser %}
            <div class="d-flex justify-content-center">
                <div class="userdata">
                    <div class="first d-flex">
                        <div class="name flex-grow-1 justify-content-center">
                            <h2>{{myuser.number}} {{myuser.name}}</h2>
                            <p class="profile_message">{{myuser.profile_message}}</p>
                        </div>
                        <!--
                        <div class="last_date">
                            <p class="last_date">최종수정일 : {{myuser.lastedit}}</p>
                        </div>
                        -->
                    </div>
                    <div class="second">
                        <h4>관심분야</h4>
                        <p class="interested">{{myuser.interested_in}}</p>
                        <h4>상세내용</h4>
                        <div class="description">
                            {{myuser.description|mark}}
                        </div>
                        {% if clubs %}
                        <h4>가입 동아리</h4>
                        <ul>
                            {% for club in clubs %}
                            <li><a class="clublink" href={% url 'club:detail' club.id %}>{{club.name}}</a></li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock content %}