club/urls.py
from django.urls import path

from . import views

app_name = 'club'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:club_id>/', views.detail, name='detail'),
    path('update/<int:club_id>/', views.update, name='update'),
    path('appli/<int:club_id>', views.appli, name='appli'),
    path('accept', views.accept, name='accept')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('club/', include('club.urls'), name='club'),
    path('event/', include('event.urls'), name='event'),
    path('post/', include('post.urls'), name='post'),
]

event/urls.py
from django.urls import path

from . import views

app_name = 'event'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:event_month>/', views.index, name='index'),
    path('detail/<int:event_id>/', views.detail, name='detail'),
    path('registration/', views.registration, name='registration'),
]

home/urls.py
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    #path('register/', views.register, name='register'),
    path('checkid/', views.checkmail, name='checkmail'),
    path('login/', auth_views.LoginView.as_view(template_name='home/home_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user/', views.user, name='user'),
    path('user/<int:userid>', views.user, name='user'),
    path('edit/', views.edit, name='edit'),
    path('manage/', views.manage, name='manage'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),
    #path('usercreate/', views.accountcreate, name='usercreate'),
]

post/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.postdetail, name='postdetail'),
    path('notice/<int:notice_id>/', views.noticedetail, name='noticedetail'),
    path('write', views.write, name='write'),
    path('like', views.like, name='like'),
    path('comment/write/<int:post_id>', views.commentwrite, name='commentwrite'),
    #path('testcase/', views.testcase, name='testcase')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Nanum+Gothic:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: "Nanum Gothic";
            z-index: 1;
            height:100%;
        }
        .img {
            min-height:100vh;
        }
    </style>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block style %}
    {% endblock style %}
    <style>
        .navbar {
            position: fixed;
            width: 100%;
            z-index: 2;
        }
        .contentblock {
            padding-top: 56px;
            padding-bottom: 42px; 
        }
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            height: 52px;
            color: black;
            background: white;
            z-index: 2;
        }
        .ftdiv {
            padding: 10px;
            width: 80%;
            margin:auto;
        }
        .ftdivdiv {
            padding: 0;
        }
        .ftdivdiv>p {
            margin : 0;
            font-size: 0.7em;
            text-align: left;
            width: fit-content;
        }
        .allow {
            font-size: 0.5em;
        }
    </style>
    <!--<script src="{% static 'js/navbar.js' %}"></script>-->
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="img">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">화명고 동아리 / 행사</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'club:index' %}">동아리</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'event:index' %}">행사</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post:index' %}">게시판</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        내 정보
                    </a>
                    <div id="myPage" class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'home:user' %}">마이페이지</a>
                            <a class="dropdown-item" href="{% url 'home:edit' %}">마이페이지 수정</a>
                            <a class="dropdown-item" href="{% url 'home:password_change' %}">비밀번호 변경</a>
                            <a class="dropdown-item" href="{% url 'home:manage' %}">동아리/행사 관리</a>
                            <a class="dropdown-item" href="{% url 'home:logout' %}">로그아웃</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'home:login' %}">로그인</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="contentblock">
        {% block content %}
        {% endblock content %}
    </div>
</div>
<footer class="footer">
    <div class="ftdiv">
        <div class="d-flex ftdivdiv flex-grow-1 flex-column">
            <p>관리자 : 20818 정정윤</p>
            <p>연락처 : hinoto04@kakao.com</p>
        </div>
    </div>
</footer>
</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% block style %}
<style>
    .text {
        width: 100%;
        font-size: 2rem;
        align-items: center;
        text-align: center;
        vertical-align: middle;
        padding-top: 52px;
    }

    @media (max-width: 768px) {
        .text {
            font-size: 1rem;
        }
    }
</style>
{% endblock style %}
{% block title %}오류{% endblock title %}
{% block content %}
    <div class="text">
        {% if text %}
            {% for t in text %}
                <p>{{t}}</p>
            {% endfor %}
        {% endif %}
    </div>
{% endblock content %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}