club/urls.py
from django.urls import path

from . import views

app_name = 'club'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:club_id>/', views.detail, name='detail'),
    path('update/<int:club_id>/', views.update, name='update'),
    path('appli/<int:club_id>', views.appli, name='appli'),
    path('accept', views.accept, name='accept')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('club/', include('club.urls'), name='club'),
    path('event/', include('event.urls'), name='event'),
    path('post/', include('post.urls'), name='post'),
]

home/urls.py
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    #path('register/', views.register, name='register'),
    path('checkid/', views.checkmail, name='checkmail'),
    path('login/', auth_views.LoginView.as_view(template_name='home/home_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user/', views.user, name='user'),
    path('user/<int:userid>', views.user, name='user'),
    path('edit/', views.edit, name='edit'),
    path('manage/', views.manage, name='manage'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),
    #path('usercreate/', views.accountcreate, name='usercreate'),
]

club/models.py
from django.db import models
from django.db.models.deletion import SET_DEFAULT
from home.models import User

class Club(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(default='', blank=True)
    category = models.CharField(max_length=20, default='기타')
    isofficial = models.BooleanField(default=False)
    member = models.IntegerField(default=1)
    member_detail = models.TextField(default='', blank=True)
    appli = models.TextField(default="", blank=True)
    create_date = models.DateTimeField(auto_created=True)
    year = models.IntegerField(default=2021)
    club_master = models.ForeignKey(User, on_delete=SET_DEFAULT, default='')
    club_teacher = models.CharField(max_length=20, default='')
    club_thumbnail = models.TextField(default='', blank=True)
    
    def __str__(self):
        return self.name

club/views.py
from django.core.mail.message import EmailMessage
from django.http.response import HttpResponse, JsonResponse
from config.pd_setting import CURRENT_YEAR
import config.settings as settings
from home.models import User
from django.shortcuts import redirect, render
from .models import Club
from django.core.paginator import Paginator
from django.contrib.auth.models import User as djangoUser

category = {'korean':'국어',
            'math':'수학',
            'english':'영어',
            'science':'과학',
            'society':'사회',
            'etc':'기타'}

def index(request):
    """클럽 목록 출력"""
    page = request.GET.get('page', '1')
    official = request.GET.get('official', '2')
    categoryeng = request.GET.get('category', 'all')
    club_list = Club.objects.all()
    club_list = Club.objects.filter(year=CURRENT_YEAR)
    if categoryeng != 'all':
        club_list = club_list.filter(category=category[categoryeng])
    if official == '0':
        club_list = club_list.filter(isofficial=False)
    elif official == '1':
        club_list = club_list.filter(isofficial=True)
    club_list = club_list.order_by('name')
    last = len(club_list)//9 if len(club_list) == 0 else len(club_list)//9+1
    
    paginator = Paginator(club_list, 9)
    page_obj = paginator.get_page(page)
    
    context = {'club_list':page_obj, 'last':last}
    return render(request, 'club/club_list.html', context)

def detail(request, club_id):
    """클럽 상세 출력"""
    try:
        club = Club.objects.get(id=club_id)
    except:
        return render(request, 'error.html', {'text': "동아리가 존재하지 않습니다."})
    else:
        member_list = []
        if club.member_detail != '':
            member_ids = club.member_detail.split(',')
            for member_id in member_ids:
                try:
                    member = User.objects.get(django_user = djangoUser.objects.get(id=member_id))
                except:
                    pass
                else:
                    member_list.append(member)
        context = {
            'club':club,
            'member_list': member_list,
            }
        return render(request, 'club/club_detail.html', context)

def update(request, club_id):
    try:
        club = Club.objects.get(id=club_id)
    except:
        return render(request, 'error.html', {'text':['동아리가 존재하지 않습니다.']})
    else:
        if request.user.is_authenticated:
            if club.club_master == User.objects.get(django_user=request.user):
                if request.method == 'GET':
                    memberlist = []
                    if club.member_detail != '':
                        for i in map(int,club.member_detail.split(',')):
                            try:
                                memberlist.append(User.objects.get(
                                    django_user = djangoUser.objects.get(id=i)
                                ))
                            except:
                                pass
                    applilist = []
                    if club.appli != '':
                        for i in map(int,club.appli.split(',')):
                            try:
                                applilist.append(User.objects.get(
                                    django_user = djangoUser.objects.get(id=i)
                                ))
                            except:
                                pass
                    context = {
                        'club': club,
                        'memberlist': memberlist,
                        'applilist': applilist
                    }
                    return render(request, 'club/club_update.html', context)
                else:
                    club.club_thumbnail = str(request.POST.get('thumbnail'))
                    club.category = category[str(request.POST.get('category'))]
                    club.description = str(request.POST.get('description'))
                    club.save()
                    return redirect('club:detail', club.id)
            else:
                return render(request, 'error.html', {'text':['권한이 없습니다.']})
        else:
            return render(request, 'error.html', {'text': ['로그인 되어 있지 않습니다.']})

def appli(request, club_id):
    if request.user.is_authenticated:
        user = request.user
        try:
            club = Club.objects.get(id=club_id)
        except:
            return render(request, 'error.html', {'text':['동아리가 존재하지 않습니다.']})
        else:
            if club.year != CURRENT_YEAR:
                return render(request, 'error.html', {'text':['올해 동아리에만 가입할 수 있습니다.']})
            if club.isofficial:
                for c in Club.objects.filter(isofficial=True).filter(year=CURRENT_YEAR):
                    if c.member_detail != '' and str(user.id) in c.member_detail.split(','):
                        return render(request, 'error.html', {'text':['이미 동아리에 가입되어 있습니다.']})
            if club.member_detail != '' and str(user.id) in club.member_detail.split(','):
                return render(request, 'error.html', {'text':['이미 해당 동아리에 가입되어 있습니다.']})
            if club.appli != '' and str(user.id) in club.appli.split(','):
                return render(request, 'error.html', {'text':['이미 해당 동아리에 신청했습니다.']}) 
            a = club.appli.split(',')
            a.append(str(user.id))
            club.appli = ','.join(a)
            club.save()
            member_list = []
            if club.member_detail != '':
                member_ids = club.member_detail.split(',')
                for member_id in member_ids:
                    try:
                        member = User.objects.get(django_user = djangoUser.objects.get(id=member_id))
                    except:
                        pass
                    else:
                        member_list.append(member)
            context = {
                'club':club,
                'member_list': member_list,
                'bool': True,
                }
            return render(request, 'club/club_detail.html', context)
    else:
        return render(request, 'error.html', {'text': ['로그인 되어 있지 않습니다.']})

def accept(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            user = request.user
            try:
                club = Club.objects.get(id=request.POST.get('clubid'))
            except:
                return JsonResponse({"result":"ClubNotFoundError"})
            if club.club_master == User.objects.get(django_user=user):
                userid = request.POST.get('userid')
                try:
                    appli = djangoUser.objects.get(id=userid)
                except:
                    return JsonResponse({'result':'NotExistUserError'})
                else:
                    if club.appli != '' and str(userid) in club.appli.split(','):
                        d = club.appli.split(',')
                        d.remove(str(userid))
                        club.appli = ','.join(d)
                    else:
                        return JsonResponse({"result":"NotAppliedError"})
                    if request.POST.get('bool') == 'true':
                        if club.member_detail != '':
                            a = club.member_detail.split(',')
                        else:
                            a = []
                        a.append(str(userid))
                        club.member_detail = ','.join(a)
                        if club.isofficial:
                            for c in Club.objects.filter(isofficial=True).filter(year=CURRENT_YEAR):
                                if c.appli != '' and str(userid) in c.appli.split(','):
                                    b = c.appli.split(',')
                                    b.remove(str(userid))
                                    c.appli = ','.join(b)
                                    c.save()
                        email = EmailMessage(f'{club.name} 가입 신청 수락 통보', f'{club.name}의 동아리원이 되신 것을 축하합니다.\n앞으로 성실한 활동 부탁드립니다.', to=[appli.email])
                        email.send()
                    else:
                        email = EmailMessage(f'{club.name} 가입 신청 거부 통보', f'귀하의 {club.name}에의 신청이 거부되었습니다. 다른 동아리에 신청 바랍니다.', to=[appli.email])
                        email.send()
                    club.save()
                    return JsonResponse({"result":"success"})
            else:
                return JsonResponse({"result":"PermissionError"})
        else:
            return JsonResponse({"result":"NotLoggedInError"})
    else:
        return render(request, 'error.html', {'text':['이 페이지는 비활성화 되어 있습니다.']})
        

templates/club/club_detail.html
{% extends 'base.html' %}
{% load static %}
{% load club_filter %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/club_detail.css' %}">
<style>
    .img {
        background-image: url({% static 'img/background.png' %});
        background-repeat: no-repeat;
        background-size: cover;
        min-height: 100vh;
    }
</style>
{% endblock style %}
{% block content %}
{% if club %}
<div class="justify-content-center">
    <div class="flex-column">
        <div class="d-flex justify-content-center thumbnail">
            <img class="d-flex clubImage" src="{{club.club_thumbnail}}" alt="{{club.name}}">
        </div>
        <div class="padding d-flex">
            <div class="detail">
                <div>
                    <div class="d-flex justify-content-center clubfirst">
                        <div class="flex-column">
                            <h1 class="clubname">{{club.name}}</h1>
                            <h2 class="clubmaster">동아리장 : {{club.club_master}}</h2>
                        </div>
                    </div>
                    <div class="clubdetail">
                        <div class='descriptionbox'>
                            <pre class="description">{{club.description | mark}}</pre>
                        </div>

                        <div class="d-flex flex-wrap justify-content-between clubsecond">
                            <div class="ma d-flex p-2 minbox flex-column">
                                <div class="p-2 justify-content-center">
                                    <h4 class="detailsecond">분야</h4>
                                    <h4 class="mintext">{{club.category}}</h4>
                                </div>
                            </div>
                            
                            <div class="ma d-flex p-2 minbox flex-column">
                                <div class="p-2 justify-content-center">
                                    <h4 class="detailsecond">구분</h4>
                                    {% if club.isofficial %} <h4 class="mintext">창체 동아리</h2>
                                    {% else %} <h4 class="mintext">자율 동아리</h2>
                                    {% endif %}
                                </div>
                            </div>

                            <div class="ma d-flex p-2 minbox flex-column">
                                <div class="p-2 justify-content-center">
                                    <h4 class="detailsecond">현재 인원</h4>
                                    <h4 class="mintext">{{club.member}}</h2>
                                </div>
                            </div>
                            
                            <div class="ma d-flex p-2 minbox flex-column">
                                <div class="p-2 justify-content-center">
                                    <h4 class="detailsecond">지도교사</h4>
                                    <h4 class="mintext">{{club.club_teacher}}</h4>
                                </div>
                            </div>
                        </div>
                        <div class="memberlist">
                            <h4 class="">동아리원 목록</h4>
                            <div class="">
                                {% if member_list %}
                                    <ul class="d-flex flex-wrap">
                                        {% for member in member_list %}
                                            <li class="membername">
                                                <a class="userlink" href="/user/{{member.django_user.id}}">{{member.number}} {{member.name}}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                {% else %}
                                    <h2>동아리원이 없습니다</h2>
                                {% endif %}
                            </div>
                        </div>
                        {% if user.is_authenticated %}
                            <div class="d-flex applibox justify-content-center">
                                <a class="btn btn-secondary" href="{% url 'club:appli' club.id %}">가입신청</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% if bool %}
<script>
    window.onload = function() {
        alert('가입신청을 완료했습니다. \n동아리장이 프로필을 보고 가입 여부를 결정합니다.\n수락 또는 거부 시 이메일로 알림이 갑니다.')
    }
</script>
{% endif %}
{% else %}
    <h1>동아리 상세 정보 로딩에 실패했습니다.</h1>
{% endif %}
{% endblock content %}

templates/club/club_list.html
{% extends 'base.html' %} <!--base.html 시작, 기본 html 형식 받아오기-->
{% load static %} <!--스태틱 파일 로드-->
{% block style %}
{{ block.super }} <link rel="stylesheet" type="text/css" href="{% static 'css/club_list.css' %}"> <!--스타일시트 로드, club/css/club_list.css 파일-->
<script src="{% static 'js/popper.min.js' %}"></script>
{% endblock style %}
{% block title %}동아리 목록{% endblock title %}<!--페이지 제목-->
{% block content %}<!--페이지 시작-->
<div class="d-flex flex-column center justify-content-center">
    <div class="title">
        <h1>동아리 목록</h1>
    </div>
    <div class="d-flex flex-column">
        <div class="d-flex filterBox justify-content-center">
            <p class="filterP">필터 : </p>
            <form id="filter" method="get" action="{% url 'club:index' %}" class="form-inline">
                <select name="official" id="filter" class="form-control form-control-sm filterSelect">
                    <option value="2">모두</option>
                    <option value="1">창체동아리</option>
                    <option value="0">자율동아리</option>
                </select>
                <select name="category" id="filter" class="form-control form-control-sm filterSelect">
                    <option value="all">모두</option>
                    <option value="korean">국어</option>
                    <option value="math">수학</option>
                    <option value="english">영어</option>
                    <option value="science">과학</option>
                    <option value="society">사회</option>
                    <option value="etc">기타</option>
                </select>
                <button class="btn" type="submit">검색</button>
            </form>
        </div>
        {% if club_list %}<!--서버에서 동아리 목록을 받았을 경우-->
            <div class="d-flex clubs">
                <ul class="d-flex wrap justify-content-center">
                    {% for club in club_list %}<!--동아리 목록 내에서 하나씩 반복-->
                        <li>
                            <div class="club d-flex flex-column">
                                <a href="{{club.id}}"><img src="{{club.club_thumbnail}}" alt="{{club.name}}" class="clubImage"></a>
                                <a href="{{club.id}}" class="clubName">{{club.name}}</a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="d-flex justify-content-center">
                <nav aria-label="Page navigation example"><!--페이지네이션 시작-->
                    <ul class="pagination marginzero">
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% if club_list.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{club_list.previous_page_number}}">{{club_list.previous_page_number}}</a></li>
                        {% endif %}
                        <li class="page-item active"><a class="page-link" href="#">{{club_list.number}}</a></li>
                        {% if club_list.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{club_list.next_page_number}}">{{club_list.next_page_number}}</a></li>
                        {% endif %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{last}}" aria-label="Last">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav><!--페이지네이션 끝-->
            </div>
        {% else %}<!--서버에서 동아리 목록을 받지 못했을 경우-->
            <div class="d-flex clubs">
                <h3>동아리가 존재하지 않습니다.</h3>
            </div>
        {% endif %}
    </div>
</div>
{% endblock content %}<!--페이지 끝-->

templates/club/club_update.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
{{ block.super }}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
<link rel="stylesheet" href="{% static 'css/club_update.css' %}">
<script>
    function accept(i, b) {
        $.ajax({
            headers: { "X-CSRFToken": '{{csrf_token}}' },
            url:'/club/accept',
            type:'POST',
            data: {
                clubid: {{club.id}},
                userid: i,
                bool: b
            },
            dataType:'json',
            success:function(response) {
                console.log(response);
                if(response.result == 'success') {
                    location.reload();
                } else if(response.result == 'NotLoggedInError') {
                    alert("로그인 되어 있지 않습니다.")
                    return;
                } else if(response.result == 'PermissionError') {
                    alert("권한이 없습니다.")
                    return;
                } else if(response.result == 'ClubNotFoundError') {
                    alert("동아리가 존재하지 않습니다.")
                    return;
                } else if(response.result == 'NotAppliedError') {
                    alert("신청이 존재하지 않습니다.")
                    return;
                }
            },
            error:function(xhr, error) {
                alert("통신 오류입니다.");
                return;
            }
        });
    }
</script>
{% endblock style %}
{% block title %}동아리 관리{% endblock title %}
{% block content %}
    <div class="d-flex flex-column all">
        <div class="d-flex justify-content-center titlebox">
            <h2>{{club.name}} 관리</h2>
        </div>
        <div class="d-flex flex-wrap">
            <div class="d-flex modify information flex-column">
                <h5>정보 수정</h5>
                <div class="formbox">
                    <form method="post" class="post-form my-3" action="{% url 'club:update' club.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="thumbnail">배너 URL</label>
                            <input type="text" class="form-control" name="thumbnail" id="thumbnail" value={{club.club_thumbnail}}>
                        </div>
                        <div class="form-group">
                            <label for="category">분류</label>
                            <select name="category" id="category" class="form-control form-control-sm">
                                <option value="korean">국어</option>
                                <option value="math">수학</option>
                                <option value="english">영어</option>
                                <option value="science">과학</option>
                                <option value="society">사회</option>
                                <option value="etc">기타</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="description">동아리 소개글</label>
                            <textarea name="description" type="description" id="Description">{{club.description}}</textarea>
                            <script>
                                var simplemde = new SimpleMDE({ 
                                    element: $("#Description")[0],
                                    spellChecker: false
                                    });
                            </script>
                        </div>
                        <button type="submit" class="btn btn-primary">저장하기</button>
                    </form>
                </div>
            </div>
            <div class="d-flex modify member flex-column">
                <h5>동아리원 관리</h5>
                <div class="managediv">
                    <div class="appli">
                        <table class="table table-striped memberlist">
                            <thead>
                                <tr>
                                <th class="memberheader" scope="col">동아리 가입 신청</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for appli in applilist %}
                                    <tr>
                                    <td class="memberbox">
                                        <div class="d-flex">
                                            <div class="d-flex flex-grow-1">
                                                <a class="membername" href="{% url 'home:user' appli.django_user.id %}">{{appli.number}} {{appli.name}}</a>
                                            </div>
                                            <div class="d-flex">
                                                <button class="applibtn acceptbtn" onclick="accept({{appli.django_user.id}}, true)"><i class="fas fa-sm fa-check"></i></button>
                                                <button class="applibtn refusebtn" onclick="accept({{appli.django_user.id}}, false)"><i class="fas fa-sm fa-times"></i></button>
                                            </div>
                                        </div>
                                    </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    </div>
                    <div class="member">
                        <table class="table table-striped memberlist">
                            <thead>
                                <tr>
                                <th class="memberheader" scope="col">동아리원 목록 <p class="membernum">총 인원: {{club.member}}</p></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for member in memberlist %}
                                    <tr>
                                    <td class="memberbox">
                                        <a class="membername" href="{% url 'home:user' member.django_user.id %}">{{member.number}} {{member.name}}</a>
                                    </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}