club/urls.py
from django.urls import path

from . import views

app_name = 'club'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:club_id>/', views.detail, name='detail'),
    path('update/<int:club_id>/', views.update, name='update'),
    path('appli/<int:club_id>', views.appli, name='appli'),
    path('accept', views.accept, name='accept')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('club/', include('club.urls'), name='club'),
    path('event/', include('event.urls'), name='event'),
    path('post/', include('post.urls'), name='post'),
]

home/urls.py
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    #path('register/', views.register, name='register'),
    path('checkid/', views.checkmail, name='checkmail'),
    path('login/', auth_views.LoginView.as_view(template_name='home/home_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user/', views.user, name='user'),
    path('user/<int:userid>', views.user, name='user'),
    path('edit/', views.edit, name='edit'),
    path('manage/', views.manage, name='manage'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),
    #path('usercreate/', views.accountcreate, name='usercreate'),
]

post/urls.py
from django.urls import path

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.postdetail, name='postdetail'),
    path('notice/<int:notice_id>/', views.noticedetail, name='noticedetail'),
    path('write', views.write, name='write'),
    path('like', views.like, name='like'),
    path('comment/write/<int:post_id>', views.commentwrite, name='commentwrite'),
    #path('testcase/', views.testcase, name='testcase')
]

post/models.py
from datetime import datetime
from django.db import models
from django.db.models.deletion import CASCADE
from club.models import Club
from home.models import User
class Notice(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    publicDate = models.DateTimeField(default=datetime(2021, 9, 12, 0, 0, 0, 0), auto_created=True)
    hotDate = models.DateTimeField(default=datetime(2021, 9, 12, 0, 0, 0, 0), auto_created=True)
    author = models.ForeignKey(User, on_delete=CASCADE)
    views = models.IntegerField(default=0)
    like = models.IntegerField(default=0)
    create_date = models.DateTimeField(auto_created=True)
    
    def __str__(self):
        return self.title
    
class Post(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    isprivate = models.BooleanField(default=True)
    isnotice = models.BooleanField(default=False)
    club = models.ForeignKey(Club, on_delete=CASCADE)
    author = models.ForeignKey(User, on_delete=CASCADE)
    views = models.IntegerField(default=0)
    like = models.IntegerField(default=0)
    create_date = models.DateTimeField(auto_created=True)
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=CASCADE, null=True)
    notice = models.ForeignKey(Notice, on_delete=CASCADE, null=True)
    author = models.ForeignKey(User, on_delete=CASCADE)
    create_date = models.DateTimeField(auto_created=True)
    
    def __str__(self):
        return self.content

post/views.py
from django.http.response import HttpResponse, JsonResponse
from post.models import Comment, Notice, Post
from home.models import User
from club.models import Club
from django.contrib.auth.models import User as djangoUser
from django.db.models import Q
import datetime
from django.utils import timezone
from django.shortcuts import redirect, render, reverse
from django.core.paginator import Paginator


def findclub(user):
    clubs = []
    for club in Club.objects.all():
        if user.id in map(int, club.member_detail.split(',')):
            clubs.append(club)
    return clubs

def getLikeList(targetuser, type = "post"):
    user = User.objects.get(django_user=targetuser)
    if type == "post":
        ul = user.like.split('/')
    else:
        ul = user.noticelike.split('/')
    likelist = list(map(int, ul[0].split(','))) if len(ul[0])>0 else []
    unlikelist = list(map(int, ul[1].split(','))) if len(ul[1])>0 else []
    return likelist, unlikelist

def index(request):
    page = request.GET.get('page', '1')
    filter = request.GET.get('view', 'all')
    last = 1
    if filter == 'notice':
        notice_list = Notice.objects.order_by('-create_date')
        paginator = Paginator(notice_list, 20)
        notice_list = paginator.get_page(page)
        post_list = None
    elif filter == 'club':
        if request.user.is_authenticated:
            clubs = findclub(request.user)
            q = Q()
            for club in clubs:
                q.add(Q(club=club), q.OR)
            notice_list = None
            post_list = Post.objects.order_by('-create_date').filter(q)
        else:
            q = Q()
            q.add(Q(hotDate__gte=timezone.localtime()), q.AND)
            q.add(Q(publicDate__lte=timezone.localtime()), q.AND)
            notice_list = Notice.objects.order_by('-create_date').filter(q)[:5]
            post_list = Post.objects.order_by('-create_date').filter(isprivate=False)
    elif filter == 'hot':
        notice_list = None
        post_list = Post.objects.order_by('-create_date').filter(isprivate=False, like__gte=5)
    else:
        q = Q()
        q.add(Q(hotDate__gte=timezone.localtime()), q.AND)
        q.add(Q(publicDate__lte=timezone.localtime()), q.AND)
        notice_list = Notice.objects.order_by('-create_date').filter(q)[:5]
        post_list = Post.objects.order_by('-create_date').filter(isprivate=False)
    if post_list:
        paginator = Paginator(post_list, 20)
        post_list = paginator.get_page(page)
    context = {
        "notice_list" : notice_list,
        "post_list" : post_list,
        "last" : last,
        "mode" : filter
    }
    return render(request, 'post/post_list.html', context)

def postdetail(request, post_id):
    try:
        like = 0 
        if request.user.is_authenticated:
            likelist, unlikelist = getLikeList(request.user)
            if post_id in likelist:
                like = 1
            elif post_id in unlikelist:
                like = -1
        post = Post.objects.get(id=post_id)
        post.views += 1
        post.save()
        comment_list = Comment.objects.filter(post=post)
    except:
        return render(request, 'error.html', {'text': ["게시글이 존재하지 않습니다."]})
    context = {
        "post": post,
        "like": like,
        "comment_list": comment_list,
    }
    return render(request, 'post/post_detail.html', context)

def noticedetail(request, notice_id):
    try:
        like = 0 
        if request.user.is_authenticated:
            likelist, unlikelist = getLikeList(request.user, "notice")
            if notice_id in likelist:
                like = 1
            elif notice_id in unlikelist:
                like = -1
        post = Notice.objects.get(id=notice_id)
        post.views += 1
        post.save()
        comment_list = Comment.objects.filter(notice=post)
    except:
        return render(request, 'error.html', {'text': ["게시글이 존재하지 않습니다."]})
    context = {
        "post": post,
        "like": like,
        "comment_list": comment_list,
    }
    return render(request, 'post/post_detail.html', context)

def write(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            post = Post(
                title = str(request.POST.get('title')),
                description = str(request.POST.get('description')),
                isprivate = bool(request.POST.get('isprivate')),
                author = User.objects.get(django_user=djangoUser.objects.get(id=request.user.id)),
                club = Club.objects.get(id=request.POST.get('club')),
                create_date = timezone.localtime()
            )
            post.save()
            return redirect(reverse('post:postdetail',args=[post.id]))
        else:
            clubs = findclub(request.user)
            context = {
                'clubs': clubs,
            }
            return render(request, 'post/post_write.html', context)
    else:
        return render(request, 'error.html', {'text': ["로그인 되어 있지 않습니다."]})

def like(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            try:
                if request.POST.get('posttype') == 'post':
                    post = Post.objects.get(id=request.POST.get('postid'))
                else:
                    post = Notice.objects.get(id=request.POST.get('postid'))
            except:
                return JsonResponse({"result":"failed"})
            else:
                if request.POST.get('posttype') == 'post':
                    likelist, unlikelist = getLikeList(request.user)
                else:
                    likelist, unlikelist = getLikeList(request.user, "notice")
                user = User.objects.get(django_user=request.user)
                if not (post.id in likelist or post.id in unlikelist):
                    if request.POST.get('like') == 'true':
                        post.like += 1
                        likelist.append(post.id)
                    else:
                        post.like -= 1
                        unlikelist.append(post.id)
                    if request.POST.get('posttype') == 'post':
                        user.like = ','.join(map(str, likelist))+'/'+','.join(map(str, unlikelist))
                    else:
                        user.noticelike = ','.join(map(str, likelist))+'/'+','.join(map(str, unlikelist))
                    user.save()
                    post.save()
                    return JsonResponse({"result":"success", "like":post.like, "change":"append"})
                else:
                    if request.POST.get('like') == 'false':
                        if post.id in likelist:
                            likelist.remove(post.id)
                            unlikelist.append(post.id)
                            change = "append"
                            post.like -= 2
                        else:
                            unlikelist.remove(post.id)
                            change = "remove"
                            post.like += 1
                    else:
                        if post.id in unlikelist:
                            likelist.append(post.id)
                            unlikelist.remove(post.id)
                            change = "append"
                            post.like += 2 
                        else:
                            likelist.remove(post.id)
                            change = "remove"
                            post.like -= 1
                    if request.POST.get('posttype') == 'post':
                        user.like = ','.join(map(str, likelist))+'/'+','.join(map(str, unlikelist))
                    else:
                        user.noticelike = ','.join(map(str, likelist))+'/'+','.join(map(str, unlikelist))
                    user.save()
                    post.save()
                    return JsonResponse({"result":"success", "like":post.like, "change":change})
            
        else:
            return JsonResponse({"result":"failed"})
    else:
        return render(request, 'error.html', {'text': ['해당 링크는 비활성화되어있습니다.']})
    
def commentwrite(request, post_id):
    if request.user.is_authenticated:
        try:
            if request.GET.get('type', 'post') == 'post':
                post = Post.objects.get(id=post_id)
            else:
                post = Notice.objects.get(id=post_id)
        except:
            return render(request, 'error.html', {'text':['글이 존재하지 않습니다.']})
        else:
            try:
                author = User.objects.get(django_user=request.user)
            except:
                return render(request, 'error.html', {'text':['사용자가 존재하지 않습니다.']})
            else:
                cmt = Comment(
                    content = str(request.POST.get('description')),
                    author = author,
                    create_date = timezone.localtime()
                )
                if request.GET.get('type', 'post') == 'post':
                    cmt.post = post
                else:
                    cmt.notice = post
                cmt.save()
                return redirect(reverse('post:postdetail',args=[post.id]))
    else:
        return render(request, 'error.html', {'text':['로그인 되어 있지 않습니다.']})

def testcase(request):
    for i in range(50):
        post = Post(title='테스트:[%03d]'%i, 
                    description='테스트내용', 
                    isprivate=False, 
                    isnotice=False, 
                    club=Club.objects.get(id=1), 
                    author=User.objects.get(id=1), 
                    views=0, 
                    like=0, 
                    create_date=timezone.localtime())
        post.save()
    return render(request, 'error.html', {'text': ["테스트케이스 생성 완료"]})

templates/post/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load post_filter %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/post_detail.css' %}">
<script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
<script>
    function like(i) {
        $.ajax({
            headers: { "X-CSRFToken": '{{csrf_token}}' },
            url:'/post/like',
            type:'POST',
            data: {
                {% if post.club %}
                posttype: "post",
                {% else %}
                posttype: "notice",
                {% endif %}
                postid: {{post.id}},
                like: i,
            },
            dataType:'json',
            success:function(response) {
                console.log(response);
                if(response.result == 'success') {
                    likenum = document.getElementById('likenum');
                    if(i) {
                        likenum.innerHTML = String(response.like);
                        if(response.change == 'append') {
                            $('#likebtn').css('display', 'none');
                            $('#likecancelbtn').css('display', 'inline-block');
                            $('#dislikebtn').css('display', 'inline-block');
                            $('#dislikecancelbtn').css('display', 'none');
                        } else {
                            $('#likebtn').css('display', 'inline-block');
                            $('#likecancelbtn').css('display', 'none');
                            $('#dislikebtn').css('display', 'inline-block');
                            $('#dislikecancelbtn').css('display', 'none');
                        }
                    } else {
                        likenum.innerHTML = String(response.like);
                        if(response.change == 'append') {
                            $('#likebtn').css('display', 'inline-block');
                            $('#likecancelbtn').css('display', 'none');
                            $('#dislikebtn').css('display', 'none');
                            $('#dislikecancelbtn').css('display', 'inline-block');
                        } else {
                            $('#likebtn').css('display', 'inline-block');
                            $('#likecancelbtn').css('display', 'none');
                            $('#dislikebtn').css('display', 'inline-block');
                            $('#dislikecancelbtn').css('display', 'none');
                        }
                    }
                } else {
                    alert("로그인 되어 있지 않습니다.");
                    return;
                }
            },
            error:function(xhr, error) {
                alert("통신 오류입니다.");
                return;
            }
        });
    }
</script>
{% endblock style %}
{% block title %}{{post.title}}{% endblock title %}
{% block content %}
    <div class="contents">
        <div class="info">
            <h6 class="title">{{post.title}}</h6>
            <div class="d-flex justify-content-between infos">
                <div class="infofirst d-flex">
                    <a class="infodetail author" href="{% url 'home:user' post.author.django_user.id %}">{{post.author}}</a>
                    <p class="infodetail notmobile">{{post.create_date}}</p>
                </div>
                <div class="infosecond d-flex">
                    <p class="infodetail views">조회 {{post.views}}</p>
                    <p class="infodetail">추천 {{post.like}}</p>
                </div>
            </div>
        </div>
        <div class="description">
            {{post.description|mark}}
        </div>
        {% if user.is_authenticated %}
        <div class="addition">
            {% if like != 1 %}
                <button id="likebtn" class="btn likebtn" onclick="like(true)"><i class="fas fa-lg fa-caret-up"></i></button>
                <button id="likecancelbtn" class="btn likecancelbtn" onclick="like(true)" 
                style="display:none"><i class="fas fa-lg fa-caret-up"></i></button>
            {% else %}
                <button id="likebtn" class="btn likebtn" onclick="like(true)" 
                style="display:none"><i class="fas fa-lg fa-caret-up"></i></button>
                <button id="likecancelbtn" class="btn likecancelbtn" onclick="like(true)"><i class="fas fa-lg fa-caret-up"></i></button>
            {% endif %}
            <p id="likenum" class="likenum">{{post.like}}</p>
            {% if like != -1 %}
                <button id="dislikebtn" class="btn dislikebtn" onclick="like(false)"><i class="fas fa-lg fa-caret-down"></i></button>
                <button id="dislikecancelbtn" class="btn dislikecancelbtn" 
                style="display:none" onclick="like(false)"><i class="fas fa-lg fa-caret-down"></i></button>
            {% else %}
                <button id="dislikebtn" class="btn dislikebtn" 
                style="display:none" onclick="like(false)"><i class="fas fa-lg fa-caret-down"></i></button>
                <button id="dislikecancelbtn" class="btn dislikecancelbtn" onclick="like(false)"><i class="fas fa-lg fa-caret-down"></i></button>
            {% endif %}
        </div>
        {% endif %}
        <div class="comments">
            {% if user.is_authenticated %}
                <div class="commentform">
                    {% if post.club %}
                        <form method="post" class="post-form" action="{% url 'post:commentwrite' post.id %}?type=post">
                    {% else %}
                        <form method="post" class="post-form" action="{% url 'post:commentwrite' post.id %}?type=notice">
                    {% endif %}
                        {% csrf_token %}
                        <div class="form-group cwritegroup">
                            <label for="description">댓글 쓰기</label>
                            <textarea name="description" type="description" id="Description" class="commenttextarea"
                            wrap="virtual" onkeyup="this.style.height='26px'; this.style.height = this.scrollHeight + 'px';"></textarea>
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary csubmit">저장하기</button>
                            </div>
                        </div>
                        
                    </form>
                </div>
            {% endif %}
            {% if comment_list %}
                {% for comment in comment_list %}
                    <div class="d-flex comment flex-column">
                        <div class="d-flex commentinfo">
                            <p class="commentauthor flex-grow-1">{{comment.author}}</p>
                            <p class="commentcreatedate">{{comment.create_date|dt}}</p>
                        </div>
                        <p class="commentcontent">{{comment.content}}</p>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/post/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load post_filter %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/post_list.css' %}">
{% endblock style %}
{% block title %}게시판{% endblock title %}
{% block content %}
    <div class="d-flex flex-column center justify-content-center">
        <div class="title">
            <h1>게시판</h1>
        </div>
        <div class="d-flex justify-content-center">
            <a class="filter" href="?view=all">전체</a>
            <a class="filter" href="?view=notice">공지</a>
            <a class="filter" href="?view=club">동아리</a>
            <a class="filter" href="?view=hot">개념글</a>
        </div>
        {% if post_list or notice_list %}
        <div class="postlist">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col" class="id">#</th>
                        <th scope="col" class="ptitle">제목</th>
                        <th scope="col" class="author">글쓴이</th>
                        <th scope="col" class="notmobile category">카테고리</th>
                        <th scope="col" class="notmobile createdate">작성일</th>
                        <th scope="col" class="views">조회</th>
                        <th scope="col" class="notmobile like">추천</th>
                    </tr>
                </thead>
                <tbody>
                    {% if notice_list %}
                        {% for notice in notice_list %}
                            <tr class="notice">
                                <th class="id" scope="row">{{notice.id}}</th>
                                <td class="ptitle"><a class="titletext" href="{% url 'post:noticedetail' notice.id %}">{{notice.title}}</a></td>
                                <td class="author"><a href="{% url 'home:user' notice.author.django_user.id %}">{{notice.author}}</a></td>
                                <td class="notmobile category">공지</td>
                                <td class="notmobile createdate">{{notice.create_date|dt}}</td>
                                <td class="views">{{notice.views}}</td>
                                <td class="notmobile like">{{notice.like}}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                    {% if post_list %}
                        {% for post in post_list %}
                            <tr class="post">
                                <th class="id" scope="row">{{post.id}}</th>
                                <td class="ptitle"><a class="titletext" href="{% url 'post:postdetail' post.id %}">{{post.title}}</a></td>
                                <td class="author"><a href="{% url 'home:user' post.author.django_user.id %}">{{post.author|username}}</a></td>
                                <td class="notmobile category"><a href="{% url 'club:detail' post.club.id %}">{{post.club.name|club}}</a></td>
                                <td class="notmobile createdate">{{post.create_date|dt}}</td>
                                <td class="views">{{post.views}}</td>
                                <td class="notmobile like">{{post.like}}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
            <div class="d-flex justify-content-end">
                <a class="btn btn-secondary" href="{% url 'post:write' %}">글쓰기</a>
            </div>
        </div>
        <div class="d-flex justify-content-center">
                <nav aria-label="Page navigation example"><!--페이지네이션 시작-->
                    <ul class="pagination marginzero">
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% if mode == 'notice' %}
                            {% if notice_list.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{notice_list.previous_page_number}}">{{notice_list.previous_page_number}}</a></li>
                            {% endif %}
                            <li class="page-item active"><a class="page-link" href="#">{{notice_list.number}}</a></li>
                            {% if notice_list.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{notice_list.next_page_number}}">{{notice_list.next_page_number}}</a></li>
                            {% endif %}
                        {% endif %}
                        {% if post_list %}
                            {% if post_list.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{post_list.previous_page_number}}">{{post_list.previous_page_number}}</a></li>
                            {% endif %}
                            <li class="page-item active"><a class="page-link" href="#">{{post_list.number}}</a></li>
                            {% if post_list.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{post_list.next_page_number}}">{{post_list.next_page_number}}</a></li>
                            {% endif %}
                        {% endif %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{last}}" aria-label="Last">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav><!--페이지네이션 끝-->
            </div>
        {% else %}
            <div class="d-flex justify-content-center nothing">
                <h3>조용합니다. 너무 조용하네요.</h3>
            </div>
        {% endif %}
    </div>
    <script>
        const URLSearch = new URLSearchParams(location.search);
        function searchParam(key) {
            return URLSearch.get(key);
        };
        if(URLSearch.has('view')) {
            jQuery(document).ready(function($) {
                $(".page-link").each(function() {
                    var elem = $(this);
                    var href = elem.attr('href');
                    elem.attr('href', href + '&view=' + searchParam('view'))
                });
            });
        };
    </script>
{% endblock content %}

templates/post/post_write.html
{% extends 'base.html' %}
{% load static %}
{% block title %}글쓰기{% endblock title %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/home_edit.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
{% endblock style %}
{% block content %}
    <div class="d-flex flex-column">
        <div class="d-flex title justify-content-center">
            <h1>글쓰기</h1>
        </div>
        <div class="d-flex justify-content-center">
            <div class="max">
                <form method="post" class="post-form my-3" action="{% url 'post:write' %}">
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                        {% for field in form %}
                            {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                            {% endif %}
                        {% endfor %}
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <label for="title">제목</label>
                        <input name="title" type="text" class="form-control" maxlength="50"
                        id="title" placeholder="글의 제목, 최대 50자까지 입력할 수 있습니다.">
                    </div>
                    <div class="form-group">
                        <div class="form-check">
                            <input name="isprivate" type="checkbox" class="form-check-input" maxlength=""
                            id="isprivate" placeholder="">
                            <label for="isprivate" class="form-check-label">동아리 한정 공개</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="club">동아리</label>
                        <select name="club" id="filter" class="form-control form-control-sm filterSelect">
                            <option value="4">자유게시판</option>
                            {% if clubs %}
                                {% for club in clubs %}
                                    <option value="{{club.id}}">{{club.name}}</option>
                                {% endfor %}
                            {% endif %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="description">본문</label>
                        <textarea name="description" type="description" id="Description"></textarea>
                        <script>
                            var simplemde = new SimpleMDE({ 
                                element: $("#Description")[0],
                                spellChecker: false
                                });
                        </script>
                    </div>
                    <button type="submit" class="btn btn-primary">저장하기</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}